web:
  build: .
  environment:
  - DISPLAY=192.168.99.1:0
  tty: true
  stdin: true
  net: host
  volumes:
  - v /tmp/.googledata:/data
  entrypoint: google-chrome
  cmd:
  - --user-data-dir=/data
  - --no-sandbox
